# Generated by Django 6.0.3 on 2026-03-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('repo_path', models.CharField(max_length=600, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000, unique=True)),
                ('sha', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('is_text', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(default='Zhongzhou', max_length=200)),
                ('repo_name', models.CharField(default='ESTELA-physics-problem-bank', max_length=200)),
                ('default_branch', models.CharField(blank=True, max_length=120)),
                ('tree_etag', models.CharField(blank=True, max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='never', max_length=30)),
                ('last_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync State',
                'verbose_name_plural': 'Sync State',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('repo_path', models.CharField(max_length=700, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('physics_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='GeneratorApp.physicsclass')),
            ],
            options={
                'ordering': ['physics_class', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('folder_path', models.CharField(max_length=900)),
                ('yaml_path', models.CharField(max_length=900, unique=True)),
                ('sha', models.CharField(max_length=64)),
                ('question_count', models.PositiveIntegerField(default=1)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='GeneratorApp.unit')),
            ],
            options={
                'ordering': ['unit', 'code', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('physics_class', 'slug'), name='uniq_unit_slug_per_class'),
        ),
    ]
